### ISSUE TITLE
Do you need an expert advisor?

### ISSUE THREAD

**Issue by websitsadiki** [agiliumtrade-ai/metaapi-python-sdk#1]
Do you work through an expert or direct connection?
What is the speed of communication with Server By milisecond Or Mirosecond
Is it less than 15 ؟

**Comment by RomanKisilenko** [comment]
Hello, latency introduced by MetaApi servers is approximately order of magnitude lower than a typical broker delay. Based on our testing the biggest components of latency are broker latency and network communication latency. 

We are going to publish performance testing report soon. Meanwhile you can run your own test to measure trading latency and terminal state synchronisation latency. 

Total latencies are usually greater than 15ms. Network communication latency is usually around 10ms and there is also some latency introduced by the broker.

**Comment by RomanKisilenko** [comment]
Hello, latency introduced by MetaApi servers is approximately order of magnitude lower than a typical broker delay. Based on our testing the biggest components of latency are broker latency and network communication latency. 

We are going to publish performance testing report soon. Meanwhile you can run your own test to measure trading latency and terminal state synchronisation latency. 

Total latencies are usually greater than 15ms. Network communication latency is usually around 10ms and there is also some latency introduced by the broker.

**Comment by RomanKisilenko** [comment]
I'll be closing this issue if no more help is required on it. Feel free to reopen if needed.
