### ISSUE TITLE
Closed positions problem

### ISSUE THREAD

**Issue by Esatyilmaz0** [agiliumtrade-ai/metaapi-python-sdk#12]
Hello, I want to get the information of the closed position with rpc connection, but an none value is returned. I can take open positions information, what should I do to get closed positions?

**Comment by RomanKisilenko** [comment]
In MT position ceases to exist when it is closed. You can retrieve information about past trades via deals history.
If you are using RPC API please check https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/examples/mt4/metaApiRpcExample.py#L65-L68
If you are using real-time streaming api please check https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/examples/mt4/metaApiSynchronizationExample.py#L65-L66
