### ISSUE TITLE
Historical Candles problem

### ISSUE THREAD

**Issue by Esatyilmaz0** [agiliumtrade-ai/metaapi-python-sdk#13]
Hello, I am disturbing, but I want to get past candles with account.get_historical_candles function, but the parameter I give as start_time returns the last date of candles. how can i solve this?

**Comment by RomanKisilenko** [comment]
Please read API contract carefully. This behaviour is expected and explicitly stated in the contract description:
```
start_time: Time to start loading candles from. Note that candles are loaded in backwards direction, so
            this should be the latest time. Leave empty to request latest candles.
```

https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/lib/metaApi/metatraderAccount.py#L470-L486
