### ISSUE TITLE
Websocket methods

### ISSUE THREAD

**Issue by brenoperucchi** [agiliumtrade-ai/metaapi-python-sdk#5]
Sorry for this dummy question. I have not succeeded to find in this SDK a method to get deal with WebSocket synchronization. [https://metaapi.cloud/docs/client/websocket/synchronizing/deals/](url)

**Comment by RomanKisilenko** [comment]
If you want to be notified when a deal arrives via websocket connection you can use streaming API like described here: https://github.com/agiliumtrade-ai/metaapi-python-sdk#receiving-synchronization-events and implement this method in your synchronization listener: https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/lib/clients/metaApi/synchronizationListener.py#L177
Please let me know if this solves your question.

**Comment by brenoperucchi** [comment]
In our expert, we need to get the information if the order on meta was closed, and using your solution with a REST API is not viable because spend too much credit of rate-limit 

Let me know if I'm close with this code below: 

```python
        listener = SynchronizationListener()
        on_connected = await listener.on_connected(account, 1)
        synchronized = await listener.on_synchronization_started(account)
        deals = await listener.on_deal_synchronization_finished(account, synchronized)
        print(deals)
```

**Comment by RomanKisilenko** [comment]
Please check this code example to see how to use synchronization listener. The difference is that the code example processes market data and you'll need on_deal_added callback in your code. https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/examples/streamQuotes/streamQuotes.py

**Comment by brenoperucchi** [comment]
I got it with your help.
