### ISSUE TITLE
TimeOutExeption on `terminal_state.wait_for_price`

### ISSUE THREAD

**Issue by elbaulp** [agiliumtrade-ai/metaapi-python-sdk#9]
I'm trying to use `StreamingMetaApiConnection.terminal_state.wait_for_price(symbol, timeout)` But I'm getting a `TimeoutExeption` even with a timeout of 60seconds. 

Am I doing something wrong?

**Comment by RomanKisilenko** [comment]
Hello, did you subscribe to market data before invoking this method? https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/lib/metaApi/streamingMetaApiConnection.py#L172-L186
